### ISSUE TITLE
uncaught error in `tm_missing_data`

### ISSUE THREAD

**Issue by chlebowa** [insightsengineering/teal.modules.general#578] opened 2023-08-17 10:31 UTC
`tm_missing_data`

### BEHAVIOR

Start example app, navigate to `Grouped b y Subject` tab, deselect `Select variables`.
An error appears in the console but not in the app (probably caught by validators as `teal::validate_inputs` message appears in output).

```
Warning: Error in if: argument is of length zero
  122: getDims
  121: catch
  120: value[[3L]]
  119: tryCatchOne
  118: tryCatchList
  117: tryCatch
  116: do
  115: hybrid_chain
  114: <reactive:plotObj>
   98: drawReactive
   85: renderFunc
   84: output$teal-main_ui-root-missing_data-module-ADRS-summary_plot-plot_main
    3: runApp
    2: print.shiny.appobj
    1: <Anonymous>
```

### APP
```
rm(list = ls())
devtools::load_all()

library(nestcolor)

ADSL <- teal.modules.general::rADSL
ADRS <- teal.modules.general::rADRS

app <- teal::init(
  data = teal.data::cdisc_data(
    teal.data::cdisc_dataset("ADSL", ADSL, code = "ADSL <- teal.modules.general::rADSL"),
    teal.data::cdisc_dataset("ADRS", ADRS, code = "ADRS <- teal.modules.general::rADRS"),
    check = TRUE
  ),
  modules = teal::modules(
    teal.modules.general::tm_missing_data(
      ggplot2_args = list(
        "Combinations Hist" = teal.widgets::ggplot2_args(
          labs = list(subtitle = "Plot produced by Missing Data Module", caption = NULL)
        ),
        "Combinations Main" = teal.widgets::ggplot2_args(labs = list(title = NULL))
      )
    )
  )
)
shinyApp(app$ui, app$server, options = list(launch.browser = TRUE))
```

**Comment by donyunardi** [comment] 2023-12-14 05:51
@chlebowa 
I can't reproduce this error anymore in `main` branch. Perhaps this is addressed?

Updated example code:

```r
data <- cdisc_data() |> within({
    ADSL <- teal.modules.general::rADSL
    ADRS <- teal.modules.general::rADRS 
  })

datanames(data) <- c("ADSL", "ADRS")

app <- init(
  data = data,
  modules = teal::modules(
    teal.modules.general::tm_missing_data(
      ggplot2_args = list(
        "Combinations Hist" = teal.widgets::ggplot2_args(
          labs = list(subtitle = "Plot produced by Missing Data Module", caption = NULL)
        ),
        "Combinations Main" = teal.widgets::ggplot2_args(labs = list(title = NULL))
      )
    )
  )
)
shinyApp(app$ui, app$server, options = list(launch.browser = TRUE))
```

**Comment by kartikeyakirar** [comment] 2023-12-14 06:08
I also confirmed that this issue is resolved and cannot be replicated on my end."

**Comment by chlebowa** [comment] 2023-12-14 06:09
Yup.

**Comment by vedhav** [comment] 2024-10-15 07:11
This seems to happen more frequently now. It is not consistent, but you can reproduce this by refreshing the app again and again until the error happens eventually.

App code to reproduce:
```r
devtools::load_all()
library(nestcolor)



app <- teal::init(
  data = teal_data() |>
    within({
      ADSL <- teal.modules.general::rADSL
      ADRS <- teal.modules.general::rADRS
    }),
  modules = teal::modules(
    teal.modules.general::tm_missing_data(
      ggplot2_args = list(
        "Combinations Hist" = teal.widgets::ggplot2_args(
          labs = list(subtitle = "Plot produced by Missing Data Module", caption = NULL)
        ),
        "Combinations Main" = teal.widgets::ggplot2_args(labs = list(title = NULL))
      )
    )
  )
)
shinyApp(app$ui, app$server)
```

Error log in console:
```r
Browsing http://127.0.0.1:4890
Warning: Error in if: argument is of length zero
  122: getDims
  121: catch
  120: value[[3L]]
  119: tryCatchOne
  118: tryCatchList
  117: tryCatch
  116: do
  115: hybrid_chain
  114: <reactive:plotObj>
   98: drawReactive
   85: renderFunc
   84: output$teal-teal_modules-missing_data-module-ADRS-summary_plot-plot_main
    3: runApp
    2: print.shiny.appobj
    1: <Anonymous>
```

**Comment by m7pr** [comment] 2024-10-15 07:13
I also saw those rarely when testing teal.goshawk modules

**Comment by chlebowa** [comment] 2024-10-15 09:19
It does seem to happen more often in apps with more modules or when the load is otherwise increased.

**Comment by averissimo** [comment] 2024-12-03 13:53
This is a problem that originates with `teal.widgets` and should be fixed with: https://github.com/insightsengineering/teal.widgets/pull/273

**Closed by averissimo** 2024-12-03 13:53 UTC
Labels: bug, core

**Comment by chlebowa** [comment] 2024-12-03 14:39
Thank you for the update, I will test at the earliest convenience.
