### ISSUE TITLE
[UAT] scale text on the variable browser plot with the plot hieght and width

### ISSUE THREAD

**Issue by kpagacz** [insightsengineering/teal.modules.general#312] opened 2022-01-20 13:34 UTC
The text in the right upper corner has a fixed size. As a consequence, it's possible to open the plot with the modal button, increase the plot size and get a very small text (almost ineligible) like this:
![image](https://user-images.githubusercontent.com/24480246/150348622-150d48f5-d693-4848-ab23-8107e939ccd2.png)

Downloading the file produces a gigantic plot with a tiny text: 
![image](https://user-images.githubusercontent.com/24480246/150348702-4d7d7e70-2d15-47c3-a149-c74ad37577a8.png)

Would be better if the text somehow scaled with the resolution.

**Comment by chlebowa** [comment] 2022-11-09 15:13
It's easy enough to do for a single `ggplot` but nested `gTree` objects are a different story.

**Comment by nikolas-burkoff** [comment] 2022-11-09 16:57
hmm - so it looks like the output from `plot_var_summary` is either a ggplot object (in which case we want to change the size of the text) or not - in which case it looks like this 
![image](https://user-images.githubusercontent.com/15201933/200891548-6d056a25-5f93-4c2e-9695-d257f281321f.png)
in which case we don't really care about the font size. 

So we could add the font size [inside this code block](https://github.com/insightsengineering/teal.modules.general/blob/main/R/tm_variable_browser.R#L945) - it's also probably easiest to have a font size slider in the UI to let users pick it rather than trying anything clever and automatic.

**Comment by nikolas-burkoff** [comment] 2022-11-09 17:06
You can also use the ggplot2_args to handle this - for example see [here](https://github.com/insightsengineering/teal.modules.general/blob/main/R/tm_a_pca.R#L425)   @Polkas is the person to ask about those and see teal.widgets for more details

**Comment by lcd2yyz** [comment] 2022-11-10 03:51
I do like the idea of font size slider, it would be a nice value added to all plot rendering through the widget. 
Potential follow-up question
- How to determine/set a font size range that make sense?
- Does the font size adjustment need to be handled differently between `ggplot` vs `grid/gTree` objects?

**Comment by nikolas-burkoff** [comment] 2022-11-10 09:19
> I do like the idea of font size slider, it would be a nice value added to all plot rendering through the widget.

So this is a nice idea but I'm not sure it's feasible as `plot_with_settings` allows lots of different types of graphical output to be displayed all of which handle font sizes differently (if you look at the km plot in tmc or the lineplot in teal.goshawk or the scatterplotmatrix in tmg) and I think different parts of graphs (axes, titles etc.) can be controlled differently too. 

In some modules in teal.osprey and teal.goshawk (and pca in tmg) we do have font size sliders but they are module specific and my suspicion is that is how it would have to be - I'd suggest adding a ticket into teal.widgets to explore further and we'd leave this issue for just the variable browser

**Comment by chlebowa** [comment] 2022-11-10 09:33
I was trying to capture the plot before downloading and adjust the font sizes there. The handler expects a `ggplot`, a `grob`, or a `gTree`, otherwise throws an error. The association module puts several plots together and they come out as a `gTree`. I honestly don't know if these size adjustments are reflected in report cards.

I think (and I am probably at least a little off) the issue is the plot output is set to 100% width of the widget and the sliders in `plot_with_settings` control just that - the size of the widgets. The plot then gets stretched or shrunk to fill that size but since the font sizes are in no way tied to the plot dimensions, they can become very small or very large compared to the plot size.

Now, @nikolas-burkoff, I didn't even get to `plot_vars_summary`. It seems to me that the `ggplot` object is converted to a `grob` before being displayed.

I also fail to see how to apply `ggplot2_args`. The help page (`teal.widgets::ggplot2_args`) is not very helpful.

@lcd2yyz Keep in mind that different text elements have different font sizes, e.g. axis labels are larger than tick labels. Strictly speaking, a font size slider would have to be applied to every one of those, which would be terrible to use. I would sooner see a font scaling slider, sort of a `cex` analog.

**Comment by Polkas** [comment] 2022-11-10 09:49
@chlebowa 

The help page of teal.widgets::ggplot2_args is not detailed as is directing you to.
`For more details see the vignette: vignette("custom-ggplot2-arguments", package = "teal.widgets").`

I agree we detailed documentation is preferable but a properly written code is self explanatory.
I want to send an important message that we should remember about Agile manifesto.

Manifesto for Agile Software Development

Individuals and interactions over processes and tools
**Working software over comprehensive documentation**
Customer collaboration over contract negotiation
Responding to change over following a plan

@donyunardi 
@pawelru

**Comment by chlebowa** [comment] 2022-11-10 13:48
> @lcd2yyz Keep in mind that different text elements have different font sizes, e.g. axis labels are larger than tick labels. Strictly speaking, a font size slider would have to be applied to every one of those, which would be terrible to use. I would sooner see a font scaling slider, sort of a cex analog.

Well, I was wrong, this __can__ be done with a single slider. The other points stand.

**Comment by pawelru** [comment] 2022-11-14 10:04
> I do like the idea of font size slider

@donyunardi @lcd2yyz @nikolas-burkoff and others

My general advise is to be very conservative when proposing a new GUI element into the module. This visualisation (Variable Browser) is one of the simplest one but still I can imagine dozens of configuration possibilities but we don't have to provide all of them! Maybe it is possible to find some defaults that in ~90% would be good enough?

I know it's a joke but it shows some extreme situation that I would like to avoid :)
> Engineers don't let engineers design user interfaces.
![image](https://user-images.githubusercontent.com/12943682/201632114-27f7b227-4170-4ca4-a9b4-51e114c7433b.png)

**Comment by nikolas-burkoff** [comment] 2022-11-15 13:47
Hi @pawelru - In lots of the other tmg modules we allow end users to control the font size so I guess it's adding the same functionality here
![Image](https://user-images.githubusercontent.com/15201933/201934484-70f63bfe-8f70-4a3d-94e3-5bb93116ca1d.png)

We could of course chose not change behaviour and close issue - it was only added by Konrad not an end user. 

If you have strong opinions please let us know ASAP as @chlebowa is working on this at the moment though we'll be happy to close it :)

**Closed** 2022-11-17 14:19 UTC
Labels: good first issue, core
