### ISSUE TITLE
Make ggtheme always selected

### ISSUE THREAD

**Issue by mhallal1** [insightsengineering/teal.modules.general#500] opened 2022-12-23 14:55 UTC
https://github.com/insightsengineering/teal.modules.general/pull/498#discussion_r1056195426

**Comment by chlebowa** [comment] 2022-12-28 11:31
I've looked at a few modules and I assume it is the same in others. The default is a vector but it is then passed through `match.arg`, so it ends up a string when it's passed to the module UI function. It seems all this needs is to replace `teal.widgets::optionalSelectInput` with `shiny::selectInput`.

**Comment by chlebowa** [comment] 2022-12-28 13:25
Pending merge of #498

**Comment by asbates** [comment] 2022-12-28 17:12
It looks to me like a theme is indeed always selected. On main, I ran the tmg bivariate example and got the following on launch

![image](https://user-images.githubusercontent.com/36482959/209847156-9fe88137-b40a-4ea4-9fd0-70b5991bc2d6.png)

I think the existing `validate` call is unnecessary. `match.arg` will take the first element of the vector ('gray') if the ggtheme argument is `NULL`. If it's a string that isn't in the allowed list (default ggtheme value), then it will fail. So as long as the theme is in the allowed list (or `NULL`), a theme will always be selected. If a 'bad' value is specified, the function `tm_g_bivariate` will fail. The app developer will then need to fix because the app won't launch locally.

Also, a bit out of scope but why is the theme specified separately from the labels? In `tm_g_bivariate` there are two arguments `ggtheme` and `ggplot2_args`. The latter is `teal.widgets::ggplot2_args` which has two arguments `labs` and `theme`.

**Comment by chlebowa** [comment] 2022-12-29 09:12
The problem is the user can **un**select it and then the plotting functions will fail with an ugly error.

**Closed** 2022-12-29 15:35 UTC
Labels: good first issue, core
