### ISSUE TITLE
[teal.modules.general] deprecated usage of `ggplot2`

### ISSUE THREAD

**Issue by chlebowa** [insightsengineering/teal.modules.general#491] opened 2022-11-17 10:51 UTC
### What happened?

After updating `ggplot2` to version `3.4.0` I am getting this warning from `tm_g_variable_browser`:
```
Warning: The dot-dot notation (`..count..`) was deprecated in ggplot2 3.4.0.
i Please use `after_stat(count)` instead.
```

Furthermore,
```
`aes_string()` was deprecated in ggplot2 3.0.0.
i Please use tidy evaluation ideoms with `aes()`
```

These should probably be updated at some point.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by nikolas-burkoff** [comment] 2023-01-06 14:08
Closed duplicate of #508 (which is solved by https://github.com/insightsengineering/teal.modules.general/pull/507 and will be in main with https://github.com/insightsengineering/teal.modules.general/pull/498

**Closed by nikolas-burkoff** 2023-01-06 14:08 UTC
Labels: core
